//! Model provider abstraction for model-agnostic LLM access.
//!
//! Defines the `ModelProvider` and `Model` traits that decouple the main loop
//! from any specific LLM backend. Provider-specific crates (in `agent-llm`)
//! implement these traits to expose their models through a unified interface.

use std::pin::Pin;
use std::sync::Arc;

use async_trait::async_trait;
use futures::Stream;
use serde::{Deserialize, Serialize};

use crate::error::ModelError;
use crate::message::{Message, Usage};
use crate::stream::{StopReason, StreamChunk};

/// A stream of model output chunks, normalized to the canonical `StreamChunk` type.
///
/// This is the primary streaming interface — callers consume chunks as they arrive
/// from the model, enabling real-time tool execution during generation.
pub type ModelStream = Pin<Box<dyn Stream<Item = Result<StreamChunk, ModelError>> + Send>>;

/// Trait for resolving model name strings to usable `Model` instances.
///
/// Providers implement this trait to expose their available models.
/// The `resolve` method accepts a model name (possibly prefixed with a provider
/// identifier like `"anthropic:claude-sonnet-4-20250514"`) and returns a ready-to-use
/// model instance.
#[async_trait]
pub trait ModelProvider: Send + Sync {
    /// Resolve a model name to a concrete `Model` implementation.
    ///
    /// Returns an error if the model name is unrecognized or the provider
    /// is unavailable.
    async fn resolve(&self, model_name: &str) -> Result<Arc<dyn Model>, ModelError>;

    /// List all model names available from this provider.
    fn available_models(&self) -> Vec<String>;
}

/// Trait representing a resolved LLM capable of streaming responses.
///
/// Implementations normalize provider-specific wire formats into the canonical
/// `StreamChunk` type before yielding them. The `complete()` method provides
/// a convenience non-streaming path that collects the full response.
#[async_trait]
pub trait Model: Send + Sync {
    /// Stream a model response as a series of `StreamChunk` items.
    ///
    /// This is the primary interface for the RunLoop, enabling concurrent
    /// tool execution during generation.
    async fn stream(&self, request: ModelRequest) -> Result<ModelStream, ModelError>;

    /// Complete a request and return the full response at once.
    ///
    /// Default implementation collects the stream into a `ModelResponse`.
    async fn complete(&self, request: ModelRequest) -> Result<ModelResponse, ModelError>;

    /// The model's canonical name (e.g., "claude-sonnet-4-20250514").
    fn name(&self) -> &str;

    /// The provider identifier (e.g., "anthropic", "openai").
    fn provider(&self) -> &str;

    /// The model's maximum context window size in tokens.
    fn context_window(&self) -> usize;

    /// The model's maximum output token limit.
    fn max_output_tokens(&self) -> usize;

    /// Whether the model supports tool use / function calling.
    fn supports_tools(&self) -> bool;

    /// Cost per million input tokens in USD.
    fn input_cost_per_million(&self) -> f64;

    /// Cost per million output tokens in USD.
    fn output_cost_per_million(&self) -> f64;
}

/// A request to send to a model for generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelRequest {
    /// System prompt / instructions for the model.
    pub system: String,

    /// The conversation history (messages) to send.
    pub messages: Vec<Message>,

    /// Tool definitions available for the model to invoke.
    pub tools: Vec<ToolDefinition>,

    /// Maximum number of output tokens to generate.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<u32>,

    /// Sampling temperature (0.0–2.0).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,

    /// JSON schema for structured output (if the model supports it).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output_schema: Option<serde_json::Value>,
}

/// A complete (non-streaming) model response.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelResponse {
    /// The content blocks generated by the model.
    pub content: Vec<ContentBlock>,

    /// Token usage statistics for this response.
    pub usage: Usage,

    /// The reason the model stopped generating.
    pub stop_reason: StopReason,
}

/// A content block within a model response (for the non-streaming path).
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ContentBlock {
    /// A text content block.
    Text { text: String },

    /// A tool use request from the model.
    ToolUse {
        id: String,
        name: String,
        input: serde_json::Value,
    },
}

/// Definition of a tool that the model can invoke.
///
/// This is passed in `ModelRequest.tools` to inform the model about
/// available tools and their expected input schemas.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ToolDefinition {
    /// The unique name of the tool.
    pub name: String,

    /// A human-readable description of what the tool does.
    pub description: String,

    /// JSON Schema describing the tool's input parameters.
    pub parameters: serde_json::Value,
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn tool_definition_serialization_roundtrip() {
        let tool = ToolDefinition {
            name: "read_file".to_string(),
            description: "Read a file from disk".to_string(),
            parameters: json!({
                "type": "object",
                "properties": {
                    "path": { "type": "string", "description": "File path to read" }
                },
                "required": ["path"]
            }),
        };
        let json_str = serde_json::to_string(&tool).unwrap();
        let deserialized: ToolDefinition = serde_json::from_str(&json_str).unwrap();
        assert_eq!(tool, deserialized);
    }

    #[test]
    fn model_request_serialization() {
        let request = ModelRequest {
            system: "You are a helpful assistant.".to_string(),
            messages: vec![Message::User {
                content: vec![crate::message::ContentBlock::Text {
                    text: "Hello".to_string(),
                }],
            }],
            tools: vec![ToolDefinition {
                name: "shell".to_string(),
                description: "Run a shell command".to_string(),
                parameters: json!({"type": "object"}),
            }],
            max_tokens: Some(4096),
            temperature: Some(0.7),
            output_schema: None,
        };
        let json_str = serde_json::to_string(&request).unwrap();
        let deserialized: ModelRequest = serde_json::from_str(&json_str).unwrap();
        assert_eq!(request.system, deserialized.system);
        assert_eq!(request.tools, deserialized.tools);
        assert_eq!(request.max_tokens, deserialized.max_tokens);
        assert_eq!(request.temperature, deserialized.temperature);
        assert_eq!(request.output_schema, deserialized.output_schema);
    }

    #[test]
    fn model_request_with_no_optional_fields() {
        let request = ModelRequest {
            system: String::new(),
            messages: vec![],
            tools: vec![],
            max_tokens: None,
            temperature: None,
            output_schema: None,
        };
        let json_str = serde_json::to_string(&request).unwrap();
        // Optional fields should be omitted from JSON
        assert!(!json_str.contains("max_tokens"));
        assert!(!json_str.contains("temperature"));
        assert!(!json_str.contains("output_schema"));
    }

    #[test]
    fn model_response_serialization_roundtrip() {
        let response = ModelResponse {
            content: vec![
                ContentBlock::Text {
                    text: "Let me help.".to_string(),
                },
                ContentBlock::ToolUse {
                    id: "tu_001".to_string(),
                    name: "read_file".to_string(),
                    input: json!({"path": "/tmp/test.txt"}),
                },
            ],
            usage: Usage {
                input_tokens: 100,
                output_tokens: 50,
                cache_read_tokens: None,
            },
            stop_reason: StopReason::ToolUse,
        };
        let json_str = serde_json::to_string(&response).unwrap();
        let deserialized: ModelResponse = serde_json::from_str(&json_str).unwrap();
        assert_eq!(response.content, deserialized.content);
        assert_eq!(response.stop_reason, deserialized.stop_reason);
    }

    #[test]
    fn content_block_text_variant() {
        let block = ContentBlock::Text {
            text: "Hello".to_string(),
        };
        let json_str = serde_json::to_string(&block).unwrap();
        let deserialized: ContentBlock = serde_json::from_str(&json_str).unwrap();
        assert_eq!(block, deserialized);
    }

    #[test]
    fn content_block_tool_use_variant() {
        let block = ContentBlock::ToolUse {
            id: "call_123".to_string(),
            name: "grep".to_string(),
            input: json!({"pattern": "TODO", "path": "src/"}),
        };
        let json_str = serde_json::to_string(&block).unwrap();
        let deserialized: ContentBlock = serde_json::from_str(&json_str).unwrap();
        assert_eq!(block, deserialized);
    }

    #[test]
    fn model_request_with_output_schema() {
        let request = ModelRequest {
            system: "Extract data.".to_string(),
            messages: vec![],
            tools: vec![],
            max_tokens: Some(1024),
            temperature: None,
            output_schema: Some(json!({
                "type": "object",
                "properties": {
                    "name": { "type": "string" },
                    "age": { "type": "integer" }
                }
            })),
        };
        let json_str = serde_json::to_string(&request).unwrap();
        assert!(json_str.contains("output_schema"));
        let deserialized: ModelRequest = serde_json::from_str(&json_str).unwrap();
        assert_eq!(request.output_schema, deserialized.output_schema);
    }

    #[test]
    fn tool_definition_equality() {
        let tool_a = ToolDefinition {
            name: "shell".to_string(),
            description: "Run command".to_string(),
            parameters: json!({"type": "object"}),
        };
        let tool_b = tool_a.clone();
        assert_eq!(tool_a, tool_b);

        let tool_c = ToolDefinition {
            name: "file_read".to_string(),
            description: "Read file".to_string(),
            parameters: json!({"type": "object"}),
        };
        assert_ne!(tool_a, tool_c);
    }
}
